import type { Metadata } from "next";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Kissa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
